language: rust
cache: cargo
rust:
  - stable
  - 1.18.0
  - beta
  - nightly

before_install:
  - sudo apt-get install -y liblzma-dev
  - sudo apt-get install -y libbz2-dev
script:
  - export PATH=$PATH:~/.cargo/bin
# - disabled until fmt stabilized: ./scripts/check-fmt.sh
# - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo clippy && cd lib && cargo clippy; cd ..; fi
  - make all
  - make travistest
  - ./scripts/e2e-test.sh
  - if [ ! -z "$RELEASE" ] ; then cd lib && make travistest; fi

env:
  global:
    - RUST_BACKTRACE=1
    - RUST_TEST_THREADS=1
  matrix:
    -
    - RELEASE=true

install:
  - ./scripts/install-sodium.sh
  - export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
  - export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH
# - disabled until fmt stabilized: cargo install -f rustfmt
# - if [ "$TRAVIS_RUST_VERSION" == "nightly" ]; then cargo install -f clippy; fi
  - ls -ahl ~/.cargo/bin/

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
