language: rust
cache: cargo
rust:
  - stable
  - beta
  - nightly
script:
  - export PATH=$PATH:~/.cargo/bin
  - ./scripts/check-fmt.sh
  - cargo clippy
  - cd lib && cargo clippy && cd ..
  - make all
  - make travistest
  - if [ ! -z "$RELEASE" ] ; then cd lib && make travistest; fi

env:
  global:
    - RUST_BACKTRACE=1
    - RUST_TEST_THREADS=1
  matrix:
    -
    - RELEASE=true

install:
- ./scripts/install-sodium.sh
- export PKG_CONFIG_PATH=$HOME/installed_libsodium/lib/pkgconfig:$PKG_CONFIG_PATH
- export LD_LIBRARY_PATH=$HOME/installed_libsodium/lib:$LD_LIBRARY_PATH
- if [ ! -x ~/.cargo/bin/cargo-fmt ]; then cargo install rustfmt; fi
- cargo install -f clippy
- ls -ahl ~/.cargo/bin/

notifications:
  webhooks:
    on_success: change  # options: [always|never|change] default: always
    on_failure: always  # options: [always|never|change] default: always
    on_start: false     # default: false
