[package]
name = "rdedup"
version = "1.0.2"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Data deduplication with compression and public key encryption. - binary"
keywords = ["data", "backup", "dedupliation", "encryption", "dedup"]
license = "MPL-2.0"
documentation = "https://dpc.github.io/rdedup-lib/"
homepage = "https://github.com/dpc/rdedup"
repository = "https://github.com/dpc/rdedup"
readme = "README.md"
exclude = ["lib/**/*"]

[[bin]]
name = "rdedup"
path = "src/bin.rs"

[dependencies]
rdedup-lib = { version = "1.0.2", path = "lib" }
log = "0.3.6"
rustc-serialize = "0.3.19"
argparse = "0.2.1"
env_logger = "0.3.4"
rpassword = "0.2.3"
slog = "~2.0.0-3"
slog-term = "~2.0.0-2"
slog-async = "~2.0.0-2"
