[package]
name = "rdedup"
version = "2.0.0-0.2"
authors = ["Dawid Ciężarkiewicz <dpc@dpc.pw>"]
description = "Data deduplication with compression and public key encryption. - binary"
keywords = ["data", "backup", "dedupliation", "encryption", "dedup"]
license = "MPL-2.0"
documentation = "https://dpc.github.io/rdedup-lib/"
homepage = "https://github.com/dpc/rdedup"
repository = "https://github.com/dpc/rdedup"
readme = "README.md"
exclude = ["lib/**/*"]

[[bin]]
name = "rdedup"
path = "src/bin.rs"

[profile.release]
opt-level = 3
debug = true
lto = true
debug-assertions = false

[workspace]

[dependencies]
rdedup-lib = { version = "2.0.0-0.2", path = "lib" }
log = "0.3.6"
rustc-serialize = "0.3.19"
clap = "2"
rpassword = "0.2.3"
slog = { version = "2", features = ["max_level_trace", "release_max_level_trace"]}
slog-term = "2"
slog-async = "2"
